$flagFile = "$PSScriptRoot\..\dialogues\dialogue_state.gd"
$maxBackups = 2

# Backup existing dialogue_state.gd
if (Test-Path $flagFile) {
    Write-Host "Backing up existing dialogue_state.gd..."
    Get-ChildItem -Path $flagFile*.bak | Sort-Object -Descending LastWriteTime | Select-Object -Skip $maxBackups | ForEach-Object {
        Remove-Item -Path $_.FullName -Force 
    }
    Copy-Item -Path $flagFile -Destination "$flagFile.bak" 
} 

# Ensure the file exists (create if it doesn't)
if (!(Test-Path $flagFile)) {
    Set-Content -Path $flagFile -Value "# This file is automatically generated. Do not edit manually." -Encoding UTF8
}

# Scan for flags and update dialogue_state.gd
$foundFlags = @{}
Get-ChildItem -Path "." -Include *.dialogue -Recurse | ForEach-Object {
    Write-Host "Parsing file: $($_.FullName)"
    $content = Get-Content -Path $_.FullName
    $content | ForEach-Object {
        if ($_ -match 'Flag\.(\w+)') {
            $flagName = $Matches[1]
            $foundFlags[$flagName] = $true

            # Check if the flag already exists with initialization
            if (!(Select-String -Path $flagFile -Pattern "static var $flagName = 0" -Quiet)) {
                # If the flag doesn't exist or doesn't have initialization, add it with initialization
                Add-Content -Path $flagFile -Value "static var $flagName = 0" -Encoding UTF8
                Write-Host "  + Added flag: $flagName"
            } 
        }
    }
}

# Delete unused variables and track changes
$updatedContent = Get-Content -Path $flagFile -Encoding UTF8
$originalVariables = $updatedContent | Where-Object { $_ -match 'static var (\w+)' } | ForEach-Object { $Matches[1] }

$updatedContent = $updatedContent | Where-Object {
    $_ -notmatch 'static var (\w+)' -or  ($_.Trim() -match 'static var (\w+)' -and $foundFlags.ContainsKey($Matches[1])) 
}

$deletedVariables = Compare-Object -ReferenceObject $originalVariables -DifferenceObject ($updatedContent | Where-Object { $_ -match 'static var (\w+)' } | ForEach-Object { $Matches[1] }) -Passthru

Set-Content -Path $flagFile -Value $updatedContent -Encoding UTF8

# Sort variables in dialogue_state.gd
$sortedContent = Get-Content -Path $flagFile -Encoding UTF8
$sortedContent | Sort-Object | Set-Content -Path $flagFile -Encoding UTF8

Write-Host "Dialogue flag generation complete."

if ($deletedVariables.Count -gt 0) {
    Write-Host "  - Deleted flags:"
    $deletedVariables | ForEach-Object { Write-Host "    - $_" }
}

pause